name: Export issues
on: [push]
jobs:
  deploy:
    name: Export issues to S3
    runs-on: ubuntu-latest
    steps:
    - name: Export issues
      uses: niteoweb/export-issues-action@v2
      with:
        repo: ${{ github.repository }}
        org: ${{ github.repository_owner }}
